server.port=8083
spring.application.name=notification-service

# Подключение к RabbitMQ в сети Docker
spring.rabbitmq.host=rabbitmq
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# Регистрация в Eureka Server
eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# 1. Открываем Actuator эндпоинты для Prometheus и мониторинга
management.endpoints.web.exposure.include=health,prometheus,info
management.endpoint.health.show-details=always

# 2. Настройка Micrometer Tracing (для OpenTelemetry)
# sampling.probability=1.0 означает, что трейсится 100% запросов (для прода обычно ставят 0.1)
management.tracing.sampling.probability=1.0

# 3. Указываем, куда отправлять трейсы (если подняли Zipkin/Tempo)
# Если Zipkin работает на localhost:9411
management.zipkin.tracing.endpoint=http://zipkin:9411/api/v2/spans