services:
  # База данных для user-service
  user-db:
    image: postgres:15-alpine
    container_name: user-postgres-db
    environment:
      POSTGRES_DB: user_db
      POSTGRES_USER: elshin_user
      POSTGRES_PASSWORD: secret_password
    ports:
      - "5432:5432"
    volumes:
      - user_db_data:/var/lib/postgresql/data
    networks:
      - beauty-network

  # База данных для booking-service
  booking-db:
    image: postgres:15-alpine
    container_name: booking-postgres-db
    environment:
      POSTGRES_DB: booking_db
      POSTGRES_USER: elshin_booking
      POSTGRES_PASSWORD: booking_password
    ports:
      - "5433:5432" # Пробрасываем внутренний порт 5432 контейнера на внешний порт 5433 хоста
    volumes:
      - booking_db_data:/var/lib/postgresql/data
    networks:
      - beauty-network

    # Наш брокер сообщений RabbitMQ
  rabbitmq:
    image: rabbitmq:3.13-management-alpine
    container_name: beauty_salon_rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"   # Порт для подключения Spring Boot (AMQP)
      - "15672:15672" # Веб-панель (Management)
    networks:
      - beauty-network

volumes:
  user_db_data:
  booking_db_data:

networks:
  beauty-network: # Общая сеть, чтобы контейнеры могли общаться друг с другом напрямую по именам сервисов
    driver: bridge