# Настройка OpenAPI для агрегации
springdoc.api-docs.path=/v3/api-docs/booking-service

spring.application.name=booking-service
server.port=8082

# Настройки подключения к новой booking_db
spring.datasource.url=jdbc:postgresql://booking-db:5432/booking_db
spring.datasource.username=elshin_booking
spring.datasource.password=booking_password
spring.datasource.driver-class-name=org.postgresql.Driver

# Настройки Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Настройки Eureka Client
eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/
eureka.instance.prefer-ip-address=true

# Глобальные настройки для всех Feign-клиентов
# Время на установку сетевого соединения (2 секунды)
feign.client.config.default.connect-timeout=2000
# Время ожидания ответа на запрос (5 секунд)
feign.client.config.default.read-timeout=5000

# Индивидуальные настройки для конкретного клиента (имя из @FeignClient(name = "user-service"))
# Для критически важных сервисов таймауты обычно делают короче
feign.client.config.user-service.connect-timeout=1000
feign.client.config.user-service.read-timeout=3000

# Настройки RabbitMQ (внутри Docker-сети хост равен beauty_salon_rabbitmq или rabbitmq)
spring.rabbitmq.host=rabbitmq
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# 1. Открываем Actuator эндпоинты для Prometheus и мониторинга
management.endpoints.web.exposure.include=health,prometheus,info
management.endpoint.health.show-details=always

# 2. Настройка Micrometer Tracing (для OpenTelemetry)
# sampling.probability=1.0 означает, что трейсится 100% запросов (для прода обычно ставят 0.1)
management.tracing.sampling.probability=1.0

# 3. Указываем, куда отправлять трейсы (если подняли Zipkin/Tempo)
# Если Zipkin работает на localhost:9411
management.zipkin.tracing.endpoint=http://zipkin:9411/api/v2/spans

# Включаем поддержку Circuit Breaker для Feign
spring.cloud.openfeign.circuitbreaker.enabled=true

# 2. Настройка таймаута для Circuit Breaker (например, 3 секунды)
resilience4j.timelimiter.instances.default.timeout-duration=3s

# 3. Базовые настройки Circuit Breaker (предохранителя)
# Если 50% запросов за последние 10 секунд упали, размыкаем цепь на 5 секунд (переходим в режим fallback)
resilience4j.circuitbreaker.instances.default.sliding-window-size=10
resilience4j.circuitbreaker.instances.default.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.default.wait-duration-in-open-state=5s

# 1. Включить экспорт всех метрик resilience4j
management.endpoint.metrics.enabled=true