spring.application.name=booking-service
server.port=8082

# Настройки подключения к новой booking_db
spring.datasource.url=jdbc:postgresql://localhost:5433/booking_db
spring.datasource.username=elshin_booking
spring.datasource.password=booking_password
spring.datasource.driver-class-name=org.postgresql.Driver

# Настройки Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Глобальные настройки для всех Feign-клиентов
# Время на установку сетевого соединения (2 секунды)
feign.client.config.default.connect-timeout=2000
# Время ожидания ответа на запрос (5 секунд)
feign.client.config.default.read-timeout=5000

# Индивидуальные настройки для конкретного клиента (имя из @FeignClient(name = "user-service"))
# Для критически важных сервисов таймауты обычно делают короче
feign.client.config.user-service.connect-timeout=1000
feign.client.config.user-service.read-timeout=3000

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest