spring.application.name=booking-service
server.port=8082

# Настройки подключения к новой booking_db
spring.datasource.url=jdbc:postgresql://localhost:5433/booking_db
spring.datasource.username=elshin_booking
spring.datasource.password=booking_password
spring.datasource.driver-class-name=org.postgresql.Driver

# Настройки Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true