server.port=8080

spring.application.name=gateway-service

# 1. Публичный маршрут для входа и регистрации (User Service)
spring.cloud.gateway.routes[0].id=auth-service-route
spring.cloud.gateway.routes[0].uri=lb://USER-SERVICE
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/v1/auth/**

# 2. Защищённый маршрут для управления пользователями
spring.cloud.gateway.routes[1].id=user-service-route
spring.cloud.gateway.routes[1].uri=lb://USER-SERVICE
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/v1/users/**
spring.cloud.gateway.routes[1].filters[0]=JwtAuthenticationFilter

# 3. Защищённый маршрут для бронирований
spring.cloud.gateway.routes[2].id=booking-service-route
spring.cloud.gateway.routes[2].uri=lb://BOOKING-SERVICE
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/v1/appointments/**
spring.cloud.gateway.routes[2].filters[0]=JwtAuthenticationFilter

# Настройка подключения к Eureka-серверу
eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/
eureka.instance.prefer-ip-address=true

# Секретный ключ для проверки JWT (должен совпадать с ключом в user-service)
jwt.secret=9a8f7e6d5c4b3a2f1e0d9c8b7a6f5e4d3c2b1a0f9e8d7c6b5a4f3e2d1c0b9a8f

# 1. Открываем Actuator эндпоинты для Prometheus и мониторинга
management.endpoints.web.exposure.include=health,prometheus,info
management.endpoint.health.show-details=always

# 2. Настройка Micrometer Tracing (для OpenTelemetry)
# sampling.probability=1.0 означает, что трейсится 100% запросов (для прода обычно ставят 0.1)
management.tracing.sampling.probability=1.0

# 3. Указываем, куда отправлять трейсы (если подняли Zipkin/Tempo)
# Если Zipkin работает на localhost:9411
management.zipkin.tracing.endpoint=http://zipkin:9411/api/v2/spans

# Отключаем дефолтное поведение, если нужно
springdoc.swagger-ui.path=/swagger-ui.html

# Настройка для автоматического обнаружения сервисов из Eureka
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true

# Настройка маршрутизации (собираем документацию с других сервисов)
springdoc.show-actuator=true

# Группа для booking-service
springdoc.group-configs[0].group=booking-service
springdoc.group-configs[0].paths-to-match=/api/v1/appointments/**
# Используем внутреннее имя контейнера booking-service и порт 8082
springdoc.group-configs[0].url=http://booking-service:8082/v3/api-docs/booking-service

# Группа для user-service
springdoc.group-configs[1].group=user-service
springdoc.group-configs[1].paths-to-match=/api/v1/users/**, /api/v1/auth/**
# Используем внутреннее имя контейнера user-service и порт 8081
springdoc.group-configs[1].url=http://user-service:8081/v3/api-docs/user-service