spring.application.name=user-service
server.port=8081

# Настройки подключения к PostgreSQL внутри сети Docker
spring.datasource.url=jdbc:postgresql://user-db:5432/user_db
spring.datasource.username=elshin_user
spring.datasource.password=secret_password
spring.datasource.driver-class-name=org.postgresql.Driver

# Настройки Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Настройки Eureka Client
eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/
eureka.instance.prefer-ip-address=true

jwt.secret=9a8f7e6d5c4b3a2f1e0d9c8b7a6f5e4d3c2b1a0f9e8d7c6b5a4f3e2d1c0b9a8f