# Настройка OpenAPI для агрегации
springdoc.api-docs.path=/v3/api-docs/user-service

spring.application.name=user-service
server.port=8081

# Настройки подключения к PostgreSQL внутри сети Docker
spring.datasource.url=jdbc:postgresql://user-db:5432/user_db
spring.datasource.username=elshin_user
spring.datasource.password=secret_password
spring.datasource.driver-class-name=org.postgresql.Driver

# Настройки Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Настройки Eureka Client
eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/
eureka.instance.prefer-ip-address=true

jwt.secret=9a8f7e6d5c4b3a2f1e0d9c8b7a6f5e4d3c2b1a0f9e8d7c6b5a4f3e2d1c0b9a8f

# 1. Открываем Actuator эндпоинты для Prometheus и мониторинга
management.endpoints.web.exposure.include=health,prometheus,info
management.endpoint.health.show-details=always

# 2. Настройка Micrometer Tracing (для OpenTelemetry)
# sampling.probability=1.0 означает, что трейсится 100% запросов (для прода обычно ставят 0.1)
management.tracing.sampling.probability=1.0

# 3. Указываем, куда отправлять трейсы (если подняли Zipkin/Tempo)
# Если Zipkin работает на localhost:9411
management.zipkin.tracing.endpoint=http://zipkin:9411/api/v2/spans